### ISSUE TITLE
Hacer un usuario para alguien externo de la pluri

### ISSUE THREAD

**Issue by Pluriversidad** [pabloselin/pluri_web#4]
Necesitamos hacer un usuario para txe quien hará curro de comunicación. 
Ya habías hecho uno para Andrea pero era con su email. Igual este lo podemos hacer de alguna manera que no sea personal. Asi no tenemos que abrir un usuario para cada persona que haga algo allí? aunque la idea es que no entre mucha gente. Pero no sé dinos tu como es mejor para tu orden del tema.
por si se necesitara el email de txe es: txeroimeser@gmail.com

**Comment by pabloselin** [comment]
Es mejor hacer una usuaria para cada persona, no es problema añadir varios y se pueden ir borrando luego de ser necesario...
Dependiendo de lo que hagan se le pueden poner diferentes roles... añadí la usuaria y mandé la clave por telegram, la usuaria también puede recuperarla desde su mail y uds pueden hacer nuevas usuarias desde: 

![image](https://github.com/pabloselin/pluri_web/assets/2073821/867ac18d-3a23-4f9e-bb12-48b4195e274c)

Y asignarle el rol que quieran (Administrador tiene todos los permisos, luego Editor tiene permisos solo para el contenido y luego hay otros más granulares que pueden revisar en : 

https://wordpress.org/documentation/article/roles-and-capabilities/
